### ISSUE TITLE
Error when running cedar-share-instances script 

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#1171]
```
Traceback (most recent call last):
 File "/srv/cedar/cedar-util/scripts/python/group_permissions_to_instances.py", line 48, in <module>
   main()
 File "/srv/cedar/cedar-util/scripts/python/group_permissions_to_instances.py", line 16, in main
   instance_ids = searcher.search_instances_of(server_address, api_key, template_id)
 File "/srv/cedar/cedar-util/scripts/python/cedar/utils/searcher.py", line 63, in search_instances_of
   return search_resources(api_key, request_url, max_count, limit_per_page)
 File "/srv/cedar/cedar-util/scripts/python/cedar/utils/searcher.py", line 35, in search_resources
   search_result = do_search(api_key, request_url, offset, query_limit)
 File "/srv/cedar/cedar-util/scripts/python/cedar/utils/searcher.py", line 86, in do_search
   return send_get_request(api_key, request_url)
 File "/srv/cedar/cedar-util/scripts/python/cedar/utils/searcher.py", line 95, in send_get_request
   document = json.loads(response.text)
 File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
   return _default_decoder.decode(s)
 File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
   obj, end = self.raw_decode(s, idx=_w(s, 0).end())
 File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
   raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
 File "/srv/cedar/cedar-util/scripts/python/group_permissions_to_instances.py", line 48, in <module>
   main()
 File "/srv/cedar/cedar-util/scripts/python/group_permissions_to_instances.py", line 16, in main
   instance_ids = searcher.search_instances_of(server_address, api_key, template_id)
 File "/srv/cedar/cedar-util/scripts/python/cedar/utils/searcher.py", line 63, in search_instances_of
   return search_resources(api_key, request_url, max_count, limit_per_page)
 File "/srv/cedar/cedar-util/scripts/python/cedar/utils/searcher.py", line 24, in search_resources
   total_count = get_total_count(api_key, request_url)
 File "/srv/cedar/cedar-util/scripts/python/cedar/utils/searcher.py", line 71, in get_total_count
   search_result = do_search(api_key, request_url, 0, 100)
 File "/srv/cedar/cedar-util/scripts/python/cedar/utils/searcher.py", line 86, in do_search
   return send_get_request(api_key, request_url)
 File "/srv/cedar/cedar-util/scripts/python/cedar/utils/searcher.py", line 95, in send_get_request
   document = json.loads(response.text)
 File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
   return _default_decoder.decode(s)
 File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
   obj, end = self.raw_decode(s, idx=_w(s, 0).end())
 File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
   raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
 File "/srv/cedar/cedar-util/scripts/python/group_permissions_to_instances.py", line 48, in <module>
   main()
 File "/srv/cedar/cedar-util/scripts/python/group_permissions_to_instances.py", line 16, in main
   instance_ids = searcher.search_instances_of(server_address, api_key, template_id)
 File "/srv/cedar/cedar-util/scripts/python/cedar/utils/searcher.py", line 63, in search_instances_of
   return search_resources(api_key, request_url, max_count, limit_per_page)
 File "/srv/cedar/cedar-util/scripts/python/cedar/utils/searcher.py", line 24, in search_resources
   total_count = get_total_count(api_key, request_url)
 File "/srv/cedar/cedar-util/scripts/python/cedar/utils/searcher.py", line 71, in get_total_count
   search_result = do_search(api_key, request_url, 0, 100)
 File "/srv/cedar/cedar-util/scripts/python/cedar/utils/searcher.py", line 86, in do_search
   return send_get_request(api_key, request_url)
 File "/srv/cedar/cedar-util/scripts/python/cedar/utils/searcher.py", line 95, in send_get_request
   document = json.loads(response.text)
 File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
   return _default_decoder.decode(s)
 File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
   obj, end = self.raw_decode(s, idx=_w(s, 0).end())
 File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
   raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by martinjoconnor** [comment]
Reran manually and it seems fine. May be related to stalled processing of permissions queues because worker server lost its connection to Redis (metadatacenter/cedar-cadsr-tools#17)

**Comment by martinjoconnor** [comment]
Likely caused by broken Redis connection. Working now.
