### ISSUE TITLE
Error when trying to save a template/element with a nested element

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-project#555]
! java.lang.IllegalArgumentException: Limit of nested fields [50] in index [cedar-search-2017-08-08t17:29:35] has been exceeded
! at org.elasticsearch.index.mapper.MapperService.checkNestedFieldsLimit(MapperService.java:538)
! at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:394)
! at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:320)
! at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:306)
! at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
! at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:480)
! at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:784)
! at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
! at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
! ... 1 common frames omitted

**Comment by marcosmro** [comment]
Modified the 'cedar-search' index settings to set the limit of nested fields to 1500 ("mapping.nested_fields.limit" : "1500")
