### ISSUE TITLE
Cron job returns error when accessing search_result["totalCount"]

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-project#920]
Traceback (most recent call last):
 File "/srv/cedar/cedar-util/scripts/group_permissions_to_instances.py", line 45, in <module>
   main()
 File "/srv/cedar/cedar-util/scripts/group_permissions_to_instances.py", line 13, in main
   instance_ids = searcher.search_instances_of(server_address, api_key, template_id)
 File "/srv/cedar/cedar-util/scripts/cedar/utils/searcher.py", line 63, in search_instances_of
   return search_resources(api_key, request_url, max_count, limit_per_page)
 File "/srv/cedar/cedar-util/scripts/cedar/utils/searcher.py", line 24, in search_resources
   total_count = get_total_count(api_key, request_url)
 File "/srv/cedar/cedar-util/scripts/cedar/utils/searcher.py", line 72, in get_total_count
   total_count = search_result["totalCount"]
KeyError: 'totalCount'

**Comment by marcosmro** [comment]
The script was using the 'search-deep' call to retrieve all instances of a template:

https://resource.metadatacenter.org/search-deep?is_based_on=https://repo.metadatacenter.org/templates/62c8b5f2-7dc9-4fff-9008-07c95a746411

The above call was returning an error 404:

{'parameters': {}, 'status': 'NOT_FOUND', 'errorMessage': None, 'errorReasonKey': None, 'statusCode': 404, 'errorKey': None}

I have updated the call to use the 'search' endpoint instead of 'search-deep'.
